server:
  address: ":8080"

api:
  version: "v1"
  routes:
    health: "/health"
    get_items: "/items"
    create_item: "/items"

logging:
  level: "info"

telemetry:
  enabled: true
  metrics_endpoint: "/metrics"

rate_limiting:
  enabled: true
  max_requests: 10
  time_window: "1m"